# Generated by Django 3.2.3 on 2021-06-01 23:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fiveg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
