# Generated by Django 3.2.3 on 2021-06-01 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiveg', '0002_alter_person_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='geographical_zone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
