# Generated by Django 3.2.3 on 2021-06-02 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fiveg', '0004_mentor'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fiveg.person'),
            preserve_default=False,
        ),
    ]
