# Generated by Django 3.2.3 on 2021-06-02 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fiveg', '0005_mentor_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=100)),
                ('background', models.CharField(max_length=100)),
                ('training', models.CharField(max_length=100)),
                ('experience_and_accomplishments', models.TextField(max_length=500)),
                ('motivation', models.TextField(max_length=100)),
                ('level', models.CharField(choices=[('Junior', 'Junior'), ('Intermediate', 'Intermediate'), ('Senior', 'Senior')], max_length=50)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiveg.person')),
            ],
        ),
    ]
