# Generated by Django 3.2.4 on 2021-06-04 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiveg', '0007_auto_20210604_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ethical_values', models.CharField(choices=[('Deontology', 'Deontology - Duty must be absolute'), ('Teleology', 'Teleology - The End justifies the means '), ('Virtue Ethics', 'Virtue Ethics - Let us aspire to be the best we can be')], max_length=20)),
            ],
        ),
    ]
